# General
url: http://localhost:3000
baseurl: ""

# Comments
comments:
  provider: false

# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Adsense
adsense: false

# Analytics
analytics:
  provider: false